spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create        # 개발환경: update / 운영은 validate 또는 none 권장
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false   # LocalDateTime 직렬화 예쁘게

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace    # SQL 바인딩 값 확인용
